/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Project' 
 * Target:  'Project' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "cs32l015.h"

/* Chipsea::Device&Standalone:HAL:ADC@1.0.0 */
#define RTE_DEVICE_HAL_ADC
/* Chipsea::Device&Standalone:HAL:AWT@1.0.0 */
#define RTE_DEVICE_HAL_AWT
/* Chipsea::Device&Standalone:HAL:BASTIM@1.0.0 */
#define RTE_DEVICE_HAL_BASETIM
/* Chipsea::Device&Standalone:HAL:BEEP@1.0.0 */
#define RTE_DEVICE_HAL_BEEP
/* Chipsea::Device&Standalone:HAL:CLKTRIM@1.0.0 */
#define RTE_DEVICE_HAL_CLKTRIM
/* Chipsea::Device&Standalone:HAL:CORTEX@1.0.0 */
#define RTE_DEVICE_HAL_CORTEX
/* Chipsea::Device&Standalone:HAL:CRC@1.0.0 */
#define RTE_DEVICE_HAL_CRC
/* Chipsea::Device&Standalone:HAL:FLASH@1.0.0 */
#define RTE_DEVICE_HAL_FLASH
/* Chipsea::Device&Standalone:HAL:FWDT@1.0.0 */
#define RTE_DEVICE_HAL_FWDT
/* Chipsea::Device&Standalone:HAL:Framework@1.0.0 */
#define RTE_DEVICE_HAL_FRAMEWORK
/* Chipsea::Device&Standalone:HAL:GPIO@1.0.0 */
#define RTE_DEVICE_HAL_GPIO
/* Chipsea::Device&Standalone:HAL:I2C@1.0.5 */
#define RTE_DEVICE_HAL_I2C
/* Chipsea::Device&Standalone:HAL:LPTIM@1.0.0 */
#define RTE_DEVICE_HAL_LPTIM
/* Chipsea::Device&Standalone:HAL:LPUART@1.0.5 */
#define RTE_DEVICE_HAL_LPUART
/* Chipsea::Device&Standalone:HAL:LVD@1.0.0 */
#define RTE_DEVICE_HAL_LVD
/* Chipsea::Device&Standalone:HAL:OPA@1.0.5 */
#define RTE_DEVICE_HAL_OPA
/* Chipsea::Device&Standalone:HAL:OWI@1.0.0 */
#define RTE_DEVICE_HAL_OWI
/* Chipsea::Device&Standalone:HAL:PCA@1.0.0 */
#define RTE_DEVICE_HAL_PCA
/* Chipsea::Device&Standalone:HAL:PWR@1.0.0 */
#define RTE_DEVICE_HAL_PWR
/* Chipsea::Device&Standalone:HAL:RCC@1.0.5 */
#define RTE_DEVICE_HAL_RCC
/* Chipsea::Device&Standalone:HAL:RTC@1.0.0 */
#define RTE_DEVICE_HAL_RTC
/* Chipsea::Device&Standalone:HAL:SPI@1.0.0 */
#define RTE_DEVICE_HAL_SPI
/* Chipsea::Device&Standalone:HAL:TIM@1.0.0 */
#define RTE_DEVICE_HAL_TIM
/* Chipsea::Device&Standalone:HAL:UART@1.0.5 */
#define RTE_DEVICE_HAL_UART
/* Chipsea::Device&Standalone:HAL:VC@1.0.5 */
#define RTE_DEVICE_HAL_VC
/* Chipsea::Device&Standalone:HAL:WWDT@1.0.0 */
#define RTE_DEVICE_HAL_WWDT


#endif /* RTE_COMPONENTS_H */
